# Generated by Django 5.2.9 on 2025-12-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depositsubscription_savingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubscription',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='depositsubscription',
            name='deposit_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.depositoptions'),
        ),
        migrations.AddField(
            model_name='savingsubscription',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingsubscription',
            name='saving_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.savingoptions'),
        ),
    ]
