# Generated by Django 5.2.9 on 2025-12-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
